# Generated by Django 5.1.5 on 2025-02-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='mediafile',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/thumbnail/'),
        ),
    ]
